const PRIMARY_COLOR = "#112761";
const BLUE_FONT_COLOR = "#0D00AA";
const GREY_FONT_COLOR = "#6B6B6B";
const WHITE_FONT_COLOR = "#FFFFFF";

export {
    PRIMARY_COLOR,
    BLUE_FONT_COLOR,
    GREY_FONT_COLOR,
    WHITE_FONT_COLOR,
}